name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      
      - name: Build and push Docker image (CPU)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.cpu
          push: true
          tags: ghcr.io/romainmendez/embeddingsapiserver:latest-cpu
          registry: ghcr.io

  build-and-push-cuda:
    runs-on: ubuntu-latest
    needs: build-and-push-cpu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      
      - name: Build and push Docker image (CUDA)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.cuda
          push: true
          tags: ghcr.io/romainmendez/embeddingsapiserver:latest-cuda
          registry: ghcr.io
          